<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ЛАБОРАТОРНІ ПАВЛЯК ВІКТОРІЯ</title>
</head>
<body>
    <h1>Павляк Вікторія ПМ-31</h1>
    <hr>
    <br>
    <a href="Lab1_Pavlyak/index.html">1 Лабораторна (готова)</a>
    <hr>
    <a href="Lab2_Pavlyak/lab2.html">2 Лабораторна (готова)</a>
    <hr>
    <a href="Lab3_Pavlyak/Lab3.html">3 Лабораторна (готова)</a>
    <hr>
    <a href="Lab4_Pavlyak/index.html">4 Лабораторна (готова)</a>
    <hr>
    <a href="Lab5_Pavlyak/lab5.html">5 Лабораторна (готова)</a>
    <hr>
    <a href="Lab6_Pavlyak/lab6.html">6 Лабораторна (готова)</a>
    <hr>
    <a href="Lab7_Pavlyak/Lab7_1.html">7 Лабораторна 1 завдання(готова)</a>
    <hr>
    <a href="Lab7_Pavlyak/Lab7_2.html">7 Лабораторна 2 завдання(готова)</a>
    <hr>
    <a href="Lab8_Pavlyak/index.html">8 Лабораторна (готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTc3ODY4NzUzMDk0/details">9 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTc3ODcyMDkyODAy/details">10 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTY0OTA0MjM4/details">11 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTY1MTEyNTk0/details">12 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTY1MTEyNjU4/details">13 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxNzg4/details">14 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxODIx/details">15 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxODQ1/details">16 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxODcx/details">17 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxOTE2/details">18 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxOTUw/details">19 Лабораторна (не готова)</a>
    <hr>
    <a href="https://classroom.google.com/c/MTUzNTA5MzIxNzcx/a/MTkxMTcyMTkxOTgx/details">20 Лабораторна (не готова)</a>

</body>
</html>

